services:
  smtp-server:
    build: ./backend/mail_server 
    container_name: mail_server
    env_file:
      - ./backend/mail_server/.env 
    ports:
      - "25:1025"
    volumes:
      - ./backend/mail_server/db:/app/db 
    environment:
      - PYTHONUNBUFFERED=1
      - MOCK_RESPONSES=0
      - AZURE_LOGGING=0
      - POSTGRES_CONNECTION_STRING=dev_admin:dev_password@postgres_dev:5432/main_db
      - INIT_DB_ON_STARTUP=1
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
  backend-api:
    build: ./backend/marketing_api
    container_name: backend_api
    env_file:
      - ./backend/marketing_api/.env
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_CONNECTION_STRING=dev_admin:dev_password@postgres_dev:5432/main_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
  postgres:
    image: postgres:15
    container_name: postgres_dev
    environment:
      POSTGRES_USER: dev_admin
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_admin -d main_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  
volumes:
  postgres_data: 